# 스코프의 생성

```js
for(var i = 0 ; i < 10 ; i++){
    var total = (total || 0) + i;
    var last = i;
    if(total > 16){
        break;
    }
}
console.log(typeof total !== 'undefined'); // true
console.log(typeof last !== 'undefined'); // true
console.log(typeof i !== 'undefined'); // true
console.log('total === ' + total + ' , last === ' , + last); // total === 21 , last === 6
```

- 다른 프로그래밍 언어에서는 for-loop의 블록 안에 선언된 변수들을 블록밖에서 조회하면 에러가 발생하지만 , 자바스크립트에서는 모든 값에 접근 할수 있다.

- 자바스크립트는 다른 언어와 달리 일반적인 블록 스코프를 따르지 않는다.

- 자바스크립트의 스코프는 특정 구문이 실행될때 새로 생성해서 스코프 체인을 생성하게 된다.

- 스코프를 생성하는 구문들은 다음과 같다. `function` , `with` , `catch`

- 다른 프로그래밍언어처럼 {}을 이용해 블록을 생성한다고 해서 스코프가 생성되는 것은 아니다.

## function 구문의 스코프 생성

```js
funcion foo(){
    var b = 'Can you access me?';
}
console.log(typeof b === 'undefined'); // true
```

- 앞의 for-loop 소스는 블록 외부에서 내부에 있는 변수들에 접근 할수 있었지만, foo() 함수 외부에서 내부에 선언된 변수에 접근 할 수 없다.

- 이것으로 function 구문을 통해서 스코프가 생성된다는 것을 알 수 있다.

## catch 구문의 스코프 생성

- with와 catch 구문도 스코프를 생성하지만 function과는 다소 다른 동작을 보여준다.

- 이 두 구문은 괄호 안에 인자로 받는 변수들만 새로운 내부 스코프에 포함되어 그다음으로 오는 블록 안에서만 접근 할 수 있다.

- 반면 블록 안에서 새로 정의한 변수들은 for-loop와 비슷하게 블록 외부에서도 접근할 수있다.

```js
try {
    throw new exception('fake exception');
} catch(err){
    var test = 'can you see me';
    console.log(err instanceof ReferenceError === true); // true
}
console.log(test === 'can you see me'); // true
console.log(typeof err === 'undefined'); // true
```

- catch 구문 내부의 파라미터로 넘겨지는 err변수는 catch블록 내부에서는 접근 할수 있지만 외부에서는 접근 할수 없다. 

- 그러나 test변수는 catch블록 외부에서도 접근 할 수 있다.

## with 구문의 스코프 생성

```js
with ({inScope : 'You can\'t see me'}) {
    var notInScope = 'but you can see me';
    console.log(inScope === 'You can\'t see me') // true
}
console.log(typeof inScope === 'undefined'); // true
console.log(notInScope === 'but you can see me'); // true
```

- catch 구문에서는 파리미터로 받은 변수만스코프 내부에서 접근할 수 있었다. with 구문도 파라미터로 받은 변수만 스코프 내부에서 접근할수 있다.

## with 구문을 활용한 문제해결

```html
<div id="div0">Click me! Div 0</div>
<div id="div1">Click me! Div 1</div>
<div id="div2">Click me! Div 2</div>
<script>
    var i , len = 3;
    for( i = 0 ; i < len ; i++){
        with ({num : i}){
            document.getElementById('div'+i).addEventListener('click',function(){
            alert('You clicked div#'+i)
        } , false )
        }
    }
</script>
<!-- 
    You clicked div#0
    You clicked div#1
    You clicked div#2
-->
```

- 먼저 with 구문은 괄호 안에 있는 파라미터를 활용하여 새로운 스코프를 만든다. 

- 그리고 num 변수의 값에 i의 값을 부여하고 클릭 이벤트에 대한 콜백 함수를 선언한다.

- 이제 클릭 이벤트의 콜백 함수는 with의 num을 참조하게 되어 고정적은 num 변수의 값인 0을 참조한다.

```
global scope    <--- with({num : 0})        <--- div0.onclick
    i = 2               num = 0                     empty scope
    len = 3     <--- with({num : 1})        <--- div1.onclick               
                        num = 1                     empty scope
                <--- with({num : 2})        <--- div2.onclick  
                        num = 2                     empty scope
```

- div0 클릭 이벤트의콜백 함수가 참조하는 스코프는 유지되고 다음 두 번째 루프에서 i값이 1일때 다시 with 구문을통해 새 스코프가 생성되면서 해당 스코프에서는 num 변수의 값을 i 값인 1로 설정한다.

- 이후 해당하는 스코프 내부에서 div1에 대한 클릭 이벤트 콜백 함수를 할당하면 div1에서의 콜백 함수는 div0과 같은 num이 아닌, 새로 생성된 num(값은 1)을 참조하게 된다.

- with 구문을 사용하지 않았던 처음 소스에서는 이벤트 함수들이 글로벌 영역에서 있는 i를 참조했다.

- 그러나 with 구문을 사용한 소스는 div에서 클릭 이벤트 콜백 함수 상위에 스코프가 형성된다. 그래서 서로 다른 별도의 num값을 참조하여 맞는 값을 출력한다.

- 스코프가 생성되는 것뿐만 아니라 스코프가 생성된 이후 스코프에서 변수 값을 지속하고 이후에 콜백 함수에서 변수에 접근할때 까지 유지하는 특성이 이러한 문제를 해결 할수 있게 도와준 것이다.