# 프로미스 이해하기

```js
const plus = new Promise((resolve , reject) => {
    const a = 1;
    const b = 2;
    if(a + b > 2) {
        resolve(a + b);
    } else {
        reject(a + b);
    }
})
plus
    .then((success) => {
        console.log(success);
    })
    .catch((fail) => {
        console.error(fail)
    })
```

- resolve(성공 메세지) reject(실패 메시지)
- resolve(msg) -> then( (msg)) reject(err) -> catch((err))

```js
const Users = {
    findOne(){
        return new Promise((res,rej) => {
            if('사용자를 찾으면') {
                res('사용자')
            } else {
                rej('못 찾았어요')
            }
        })
    }
    remove(){ return new Promise(...) } 
    update(){ return new Promise(...) } 
}
Users.findOne()
    .then()
    .catch()
```

- Promise를 지원하는 메서드는 내부적으로 지원해주기 때문에 사용 가능합니다.

- 콜백을 프로미스로 바꿀수 있는게 아니라 내부적으로 프로미스를 지원해야지 할 수 있다.

```js
const condition = true; // true 면 resolve false면 reject
const promise = new Promise( (resolve , reject) => {
    if(condition) {
        resolve('성공')
    } else {
        reject('실패')
    }
})
promise
    .then( (message) => {
        console.log(message) // 성공(resolve)한 경우 실행
    })
    .catch( (error) => {
        console.error(error) // 실패(reject) 한 경우 실행
    })
```

```js
promise
    .then( (message) => {
        return new Promise((resolve, reject) => {
            resolve(message2);
        })
    })
    .then((message2) => {
        console.log(message2);
        return new Promise((resolve , reject) => {
            resolve(message3);
        })
    })
    .then((message3) => {
        console.log(message3);
    })
    .catch((error) => {
        console.error(error);
    })
```

- then에 리턴 값이 있으면 다음 then으로 넘어갑니다. Promise를 리턴하면 resolve나 reject 되어 넘어갑니다.